export const ROUTES = {
    HOME: '/',
    JOBS: '/jobs',
    JOB_DETAILS: (id: number) => `/jobs/${id}`,
    JOB_DETAILS_PATTERN: '/jobs/:id',
    MY_JOB_OFFERS: '/my-job-offers',
    MY_JOB_OFFER_DETAILS: (id: number) => `/my-job-offers/${id}`,
    MY_JOB_OFFER_DETAILS_PATTERN: '/my-job-offers/:id',
    JOB_OFFER_CREATE: '/my-job-offers/create',
    JOB_OFFER_EDIT: (id: number) => `/my-job-offers/${id}/edit`,
    JOB_OFFER_EDIT_PATTERN: '/my-job-offers/:id/edit',
    MY_APPLICATIONS: '/my-applications',
    MY_APPLICATION_DETAILS: (id: number) => `/my-applications/${id}`,
    MY_APPLICATION_DETAILS_PATTERN: '/my-applications/:id',
    MY_APPLICATION_EDIT: (id: number) => `/my-applications/${id}/edit`,
    MY_APPLICATION_EDIT_PATTERN: '/my-applications/:id/edit',
    PROFILE: '/profile',
    LOGIN: '/login',
    REGISTER: '/register',
    CATEGORIES: '/categories',
    CATEGORY_CREATE: '/categories/create',
    CATEGORY_DETAILS: (id: number) => `/categories/${id}`,
    CATEGORY_DETAILS_PATTERN: '/categories/:id',
} as const;